# permissions to do edit offlines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: offline-editor-role
rules:
- apiGroups:
  - colocation.cmyun.io
  resources:
  - offlines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - colocation.cmyun.io
  resources:
  - offlines/status
  verbs:
  - get
  - patch
  - update
