# permissions to do viewer offlines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: offline-viewer-role
rules:
- apiGroups:
  - colocation.cmyun.io
  resources:
  - offlines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - colocation.cmyun.io
  resources:
  - offlines/status
  verbs:
  - get
