# permissions to do edit onlines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: online-editor-role
rules:
- apiGroups:
  - colocation.cmyun.io
  resources:
  - onlines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - colocation.cmyun.io
  resources:
  - onlines/status
  verbs:
  - get
  - patch
  - update
